spring:
  cloud:
    compatibility-verifier:
      enabled : false
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: '@project.name@'
    description: '@project.description@'
  profiles:
    active: local
  messages:
    basename: messages/messages
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  lifecycle:
    timeout-per-shutdown-phase: "50s"

server:
  servlet:
    context-path: /
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /_monitoring
      exposure:
        include: "health,prometheus"

logging:
  facility: Reservation-API
  level:
    springfox.documentation: ERROR
    org.springframework: ERROR
    org.springframework.kafka: ERROR
    org.apache.kafka: ERROR
    org.hibernate: ERROR
    org.apache.http: ERROR
    org.apache.commons: ERROR
    com.zaxxer.hikari: INFO

feign:
  client:
    config:
      default:
        loggerLevel: basic
      example-api:
        url:
        connectTimeout: 2000
        readTimeout: 5000

springdoc:
  swagger-ui:
    path: /

---
spring:
  config:
    activate:
      on-profile: stage, prod

logging:
  pattern:
    console: "{\"time\": \"%d\", \"level\": \"%p\", \"agent-name\": \"%X{x-agentname}\", \"correlation-id\": \"%X{correlation-id}\", \"executor-user\": \"%X{x-executor-user}\", \"remote-host\": \"%X{x-remote-host}\", \"source\": \"%logger{63}:%L\", \"msg\": \"%replace(%replace(%m%wEx{6}){'[\r\n]+', '\\n'}){'\"', ''}%nopex\", \"app_name\": \"@project.name@\", \"log_type\": \"%marker\"}%n"
  level:
    org.springframework: WARN
