### Get Blocked Dates
GET {{host}}/api/v1/blocked-dates?type=KITCHEN_ICON&placement=CHANNEL&priority=1&startDate=2025-06-01&endDate=
Authorization: Basic bG9jYWxjb21tZXJjZS1hZHMtaW50ZXJuYWwtdG9rZW4=
x-correlationId: 111

### Save Blocked Dates
POST {{host}}/api/v1/blocked-dates
Authorization: Basic bG9jYWxjb21tZXJjZS1hZHMtaW50ZXJuYWwtdG9rZW4=
x-correlationId: 222
Content-Type: application/json

{
  "type": "KITCHEN_ICON",
  "placement": "CHANNEL",
  "priority": 1,
  "blockedDates": [
    "2025-08-01",
    "2025-07-02"

  ]
}

### Delete Blocked Dates
DELETE {{host}}/api/v1/blocked-dates
Authorization: Basic bG9jYWxjb21tZXJjZS1hZHMtaW50ZXJuYWwtdG9rZW4=
x-correlationId: 222
Content-Type: application/json

{
  "type": "KITCHEN_ICON",
  "placement": "CHANNEL",
  "priority": 1,
  "dates": ["2025-07-01", "2025-07-02"]
}